// frontend/src/components/Navbar/Navbar.tsx
import Link from "next/link";
import NavLink, { NavLinkProps } from "./NavLink";

export default function () {
  const navItems: NavLinkProps[] = [
    { text: "Home", to: "/" },
    { text: "New", to: "/new" },
    {
      text: "Log In",
      to: "/login",
      classes: "bg-primary !text-white py-2 px-4 rounded-lg font-semibold",
    },
    { text: "Sign In", to: "/signin", classes: "text-primary font-semibold" },
  ];

  return (
    <nav className="w-full h-24 border-b-2 border-b-textColor/20">
      <div className="w-4/5 h-full mx-auto flex flex-row">
        <ul className="w-1/3 flex flex-row items-center justify-start">
          <li className="text-4xl font-semibold text-primary">
            <Link href={"/"}>BlogApp</Link>
          </li>
        </ul>
        <ul className="w-2/3 flex flex-row items-center justify-end gap-10 mx-10">
          {navItems.map((navItem) => (
            <NavLink {...navItem} key={navItem.text} />
          ))}
        </ul>
      </div>
    </nav>
  );
}

// angular/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { LinkProps } from '../components/link/link.component';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
})
export class NavbarComponent {
  routes: LinkProps[] = [
    { text: 'Home', link: '/' },
    { text: 'New', link: '/new' },
    {
      text: 'Log In',
      link: '/login',
      classes: 'bg-primary !text-white py-2 px-4 rounded-lg font-semibold',
    },
    { text: 'Sign In', link: '/signin', classes: 'text-primary font-semibold' },
  ];
}

<nav class="w-full h-24 border-b-2 border-b-textColor/20">
  <div class="w-4/5 h-full mx-auto flex flex-row">
    <ul class="w-1/3 flex flex-row items-center justify-start">
      <li class="text-4xl font-semibold text-primary">
        <a routerLink="/">BlogApp</a>
      </li>
    </ul>
    <ul class="w-2/3 flex flex-row items-center justify-end gap-10 mx-10">
      <app-link
        *ngFor="let route of routes"
        link="{{ route.link }}"
        text="{{ route.text }}"
        classes="{{ route.classes }}"
      ></app-link>
    </ul>
  </div>
</nav>
