// angular/src/app/components/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent {
  @Input() title = '';
  @Input() subtitle = '';
}

<hgroup class="flex flex-col gap-2 mt-6">
  <h1 class="text-6xl text-primary font-bold">{{ title }}</h1>
  <h2 class="text-4xl mt-4">{{ subtitle }}</h2>
</hgroup>

// frontend/src/components/Header.tsx
export default function Header({
  props: { title, subtitle },
}: {
  props: { title: string; subtitle: string };
}) {
  return (
    <hgroup className="flex flex-col gap-2 mt-6">
      <h1 className="text-6xl text-primary font-bold">{title}</h1>
      <h2 className="text-4xl mt-4">{subtitle}</h2>
    </hgroup>
  );
}
